### Получаем параметры квартиры
GET http://localhost:8000/api/getparams?url=flat/309402371
Content-Type: application/json

### Получаем список моделей
GET http://localhost:8000/api/list_models
Content-Type: application/json